### PR TITLE
new corrected commit for A4 pos

### PR DESCRIPTION
**Pull request by drparamita**
We made changes to the position of A4 vpol antennas, cable delay, calpulser depth, "corrected channel map" etc. Position verified with Spice, deep and local cp. 
24th June 2024 

see 
1. **docdb note** https://aradocs.wipac.wisc.edu/cgi-bin/DocDB/ShowDocument?docid=3124
2. **analysis call presentation :** https://aradocs.wipac.wisc.edu/0030/003085/001/A4_latest_for_reco.pdf

### CODE REVIEW

**Review by jflaherty13 — APPROVED** [review]
I think this looks good.  It makes the changes you sent me previously, which vastly improved my A4 reconstruction of SPICE events.

**Comment by drparamita** [comment]
Thanks @jflaherty13 for checking.

**Comment by marcomuzio** [comment]
Hey @drparamita, thanks for making these updates and additional documentation! I've gone through and confirmed that the updated sql tables agree with the documents you linked above. I do have two concerns which would be good to address before we merge:

1. The RF channel numbering in your tables doesn't follow our usual convention. Historically, when borehole number and string number don't align we have followed the convention of using the string number to define RF channels. Ideally we would do this again, but it's probably not the end of the world if we don't. My bigger concern though is that the RF channel assignments you've made also don't correspond to our usual RF channels definitions using the borehole number. Whichever we use to define RF channel (string number or borehole number) we should be consistent with the convention in slide 19 [here](https://aradocs.wipac.wisc.edu/cgi-bin/DocDB/ShowDocument?docid=2188). 

2. In the update of the calpulser coordinates, it looks like you assigned the Vpol & Hpol calpulser the same depth, which can't be true in reality. Can you update the Hpol depth to have the same relative spacing to the Vpol as was in the default table?

**Comment by marcomuzio** [comment]
Hi @drparamita, I went through and made these corrections. Can you double check things look correct. The RF-electric channel mapping is different in order to make the RF channel convention consistent but this should still preserve the electric channel-to-coordinate mapping. If it looks good can you also update your reference document? Thanks!

**Comment by marcomuzio** [comment]
I agree, I think @drparamita was just updating some documentation?

**Pull request merged**
