### PR TITLE
Livetime configuration functionality

### PR DESCRIPTION
**Pull request by marcomuzio**
Adds functions to the AraQualCuts class to determine the livetime configuration of a given run and station. Also adds new directory to store livetime configuration logs.

### CODE REVIEW

**Comment by clark2668** [comment]
Thanks Marco! Two question:

1. Do you have a strong preference between tab and comma separated? I'm partial to commas: I find them easier to parse, and harder to screw up across editors.
2. Is there a reason these files are in AraRoot and not the runlogs repo? I guess just for simplicity?

**Comment by marcomuzio** [comment]
1. No strong preference, I can switch it to comma separated. No problem.
2. My thinking was that AraRoot should ship with these files so that it's self-contained.

**Comment by clark2668** [comment]
1. I leave it up to you. If white-space-separated works, then it's fine with me.
2. Okay, understandable.
3. I sent you a few ideas for further hardening the code, listing them here for completeness:

- What happens if there is an unexpected empty line?
- What happens if a column is missing?
- What happens if a run or config is negative or decimal/float?

**Comment by marcomuzio** [comment]
^Just pushed some updates that I believe address all of these possibilities.

**Comment by clark2668** [comment]
Looks excellent, thanks Marco. My only last comment is that it might be nice if there was a column label in the file, like. But that's gravy.

RunNo, Config
1000, 2
1200, 5
...

**Pull request merged**
